# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'AmazonChimeSDKDemoPods' do
  use_frameworks!
  # Pods for AmazonChimeSDKDemoPods
  pod 'AmazonChimeSDK-Bitcode'
  pod 'AmazonChimeSDKMachineLearning-Bitcode'
end

target 'AmazonChimeSDKDemoBroadcastPods' do
  use_frameworks!
  # Pods for AmazonChimeSDKDemoBroadcastPods
  pod 'AmazonChimeSDK-Bitcode'
end
